FROM debian:buster

RUN apt update
RUN apt upgrade -y 
RUN apt install -y nginx
RUN apt install -y vim
RUN apt install -y openssl
RUN sed -i 's/ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;/ssl_protocols TLSv1.2;/g' /etc/nginx/nginx.conf
COPY ./tools/run.sh /
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/mokhames.key -out /etc/ssl/certs/mokhames.crt -subj "/C=MA/ST=SRAGHNA /L=Benguerir /O=1337/OU=Cluster/CN=localhost/emailAddress=mokhames@student.1337.ma"

COPY ./conf/default /etc/nginx/sites-available/
# RUN sh run.sh

CMD ["sh", "run.sh"]
EXPOSE 443